"""wikidata fields

Revision ID: 0da071801867
Revises: 3ff3602cf495
Create Date: 2026-10-05 15:13:24.339502

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0da071801867"
down_revision: str | Sequence[str] | None = "3ff3602cf495"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_audio_form_id"), "audio", ["form_id", "url"])
    op.add_column("concept", sa.Column("description_en", sa.String(length=500), nullable=True))
    op.add_column("concept", sa.Column("description_uk", sa.String(length=500), nullable=True))
    op.add_column(
        "form", sa.Column("is_primary", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column("form", sa.Column("external_id", sa.String(length=50), nullable=True))
    op.create_unique_constraint(
        op.f("uq_form_concept_id"), "form", ["concept_id", "variety_id", "spelling"]
    )
    op.add_column("variety", sa.Column("wikidata_id", sa.String(length=20), nullable=True))
    op.create_unique_constraint(op.f("uq_variety_wikidata_id"), "variety", ["wikidata_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_variety_wikidata_id"), "variety", type_="unique")
    op.drop_column("variety", "wikidata_id")
    op.drop_constraint(op.f("uq_form_concept_id"), "form", type_="unique")
    op.drop_column("form", "external_id")
    op.drop_column("form", "is_primary")
    op.drop_column("concept", "description_uk")
    op.drop_column("concept", "description_en")
    op.drop_constraint(op.f("uq_audio_form_id"), "audio", type_="unique")
    # ### end Alembic commands ###
