"""region label point

Revision ID: 1c3d5a4eb965
Revises: 0da071801867
Create Date: 2026-10-05 20:23:13.796744

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = "1c3d5a4eb965"
down_revision: str | Sequence[str] | None = "0da071801867"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_geospatial_column(
        "region",
        sa.Column(
            "label_point",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
    )
    op.add_column("region", sa.Column("label_rank", sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("region", "label_rank")
    op.drop_geospatial_column("region", "label_point")
    # ### end Alembic commands ###
