"""form contributor

Revision ID: 2b3ee47de3a2
Revises: 586470ae68fc
Create Date: 2026-10-07 16:21:27.375538

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b3ee47de3a2"
down_revision: str | Sequence[str] | None = "586470ae68fc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("form", sa.Column("contributor", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("form", "contributor")
    # ### end Alembic commands ###
