"""initial lexicon schema

Revision ID: 3ff3602cf495
Revises:
Create Date: 2026-10-05 14:57:51.192144

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = "3ff3602cf495"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "concept",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("gloss_en", sa.String(length=200), nullable=False),
        sa.Column("gloss_uk", sa.String(length=200), nullable=True),
        sa.Column("wikidata_id", sa.String(length=20), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_concept")),
        sa.UniqueConstraint("wikidata_id", name=op.f("uq_concept_wikidata_id")),
    )
    op.create_geospatial_table(
        "region",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name_en", sa.String(length=200), nullable=False),
        sa.Column("name_uk", sa.String(length=200), nullable=True),
        sa.Column("level", sa.String(length=10), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column(
            "geom",
            Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["region.id"], name=op.f("fk_region_parent_id_region")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_region")),
        sa.UniqueConstraint("level", "code", name=op.f("uq_region_level")),
    )
    op.create_geospatial_index(
        "idx_region_geom",
        "region",
        ["geom"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_table(
        "source",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("license", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source")),
        sa.UniqueConstraint("name", name=op.f("uq_source_name")),
    )
    op.create_table(
        "variety",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name_en", sa.String(length=200), nullable=False),
        sa.Column("name_uk", sa.String(length=200), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("iso639_3", sa.String(length=3), nullable=True),
        sa.Column("glottocode", sa.String(length=8), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["variety.id"], name=op.f("fk_variety_parent_id_variety")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_variety")),
        sa.UniqueConstraint("glottocode", name=op.f("uq_variety_glottocode")),
    )
    op.create_index(op.f("ix_variety_iso639_3"), "variety", ["iso639_3"], unique=False)
    op.create_table(
        "form",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("concept_id", sa.Integer(), nullable=False),
        sa.Column("variety_id", sa.Integer(), nullable=False),
        sa.Column("spelling", sa.String(length=200), nullable=False),
        sa.Column("ipa", sa.String(length=200), nullable=True),
        sa.Column("transliteration", sa.String(length=200), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["concept_id"], ["concept.id"], name=op.f("fk_form_concept_id_concept")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["source.id"], name=op.f("fk_form_source_id_source")
        ),
        sa.ForeignKeyConstraint(
            ["variety_id"], ["variety.id"], name=op.f("fk_form_variety_id_variety")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_form")),
    )
    op.create_index(op.f("ix_form_concept_id"), "form", ["concept_id"], unique=False)
    op.create_index(op.f("ix_form_spelling"), "form", ["spelling"], unique=False)
    op.create_index(op.f("ix_form_variety_id"), "form", ["variety_id"], unique=False)
    op.create_table(
        "variety_region",
        sa.Column("variety_id", sa.Integer(), nullable=False),
        sa.Column("region_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["region.id"],
            name=op.f("fk_variety_region_region_id_region"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["variety_id"],
            ["variety.id"],
            name=op.f("fk_variety_region_variety_id_variety"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("variety_id", "region_id", name=op.f("pk_variety_region")),
    )
    op.create_table(
        "audio",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("form_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("speaker", sa.String(length=200), nullable=True),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("license", sa.String(length=100), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["form_id"], ["form.id"], name=op.f("fk_audio_form_id_form"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["source.id"], name=op.f("fk_audio_source_id_source")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audio")),
    )
    op.create_index(op.f("ix_audio_form_id"), "audio", ["form_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audio_form_id"), table_name="audio")
    op.drop_table("audio")
    op.drop_table("variety_region")
    op.drop_index(op.f("ix_form_variety_id"), table_name="form")
    op.drop_index(op.f("ix_form_spelling"), table_name="form")
    op.drop_index(op.f("ix_form_concept_id"), table_name="form")
    op.drop_table("form")
    op.drop_index(op.f("ix_variety_iso639_3"), table_name="variety")
    op.drop_table("variety")
    op.drop_table("source")
    op.drop_geospatial_index(
        "idx_region_geom", table_name="region", postgresql_using="gist", column_name="geom"
    )
    op.drop_geospatial_table("region")
    op.drop_table("concept")
    # ### end Alembic commands ###
