"""variety code

Revision ID: 586470ae68fc
Revises: e1dd7d59a60e
Create Date: 2026-10-07 15:40:11.261819

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "586470ae68fc"
down_revision: str | Sequence[str] | None = "e1dd7d59a60e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("variety", sa.Column("code", sa.String(length=40), nullable=True))
    op.execute("UPDATE variety SET code = coalesce(iso639_3, 'variety-' || id)")
    op.alter_column("variety", "code", nullable=False)
    op.create_unique_constraint(op.f("uq_variety_code"), "variety", ["code"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_variety_code"), "variety", type_="unique")
    op.drop_column("variety", "code")
    # ### end Alembic commands ###
