"""concept slug

Revision ID: bab76cdd951f
Revises: 1c3d5a4eb965
Create Date: 2026-10-05 20:30:37.469725

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bab76cdd951f"
down_revision: str | Sequence[str] | None = "1c3d5a4eb965"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("concept", sa.Column("slug", sa.String(length=120), nullable=True))
    op.create_unique_constraint(op.f("uq_concept_slug"), "concept", ["slug"])
    # Backfill existing concepts (same rule as app.slugs.ASSIGN_MISSING_SLUGS)
    op.execute("""
        WITH base AS (
            SELECT id, wikidata_id,
                   trim(both '-' from regexp_replace(lower(gloss_en), '[^a-z0-9]+', '-', 'g'))
                   AS slug
            FROM concept
        ), counted AS (
            SELECT *, count(*) OVER (PARTITION BY slug) AS n FROM base
        )
        UPDATE concept c
        SET slug = CASE
            WHEN counted.slug = '' THEN lower(coalesce(counted.wikidata_id, 'concept-' || c.id))
            WHEN counted.n > 1
                THEN counted.slug || '-' || lower(coalesce(counted.wikidata_id, c.id::text))
            ELSE counted.slug
        END
        FROM counted
        WHERE c.id = counted.id
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_concept_slug"), "concept", type_="unique")
    op.drop_column("concept", "slug")
    # ### end Alembic commands ###
