"""form status

Revision ID: e1dd7d59a60e
Revises: bab76cdd951f
Create Date: 2026-10-06 08:16:59.460056

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e1dd7d59a60e"
down_revision: str | Sequence[str] | None = "bab76cdd951f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "form", sa.Column("status", sa.String(length=10), server_default="approved", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("form", "status")
    # ### end Alembic commands ###
